sonar.sources=tenantCrm/src/main/java,tenantCrm/src/main/resources
sonar.tests=tenantCrm/src/test/java
sonar.coverage.exclusions=tenantCrm/src/main/resources/static/**,tenantCrm/src/main/resources/templates/**,tenantCrm/src/test/java/**
