sonar.sources=tenantCrm/src/main/java,tenantCrm/src/main/resources
sonar.tests=tenantCrm/src/test/java
sonar.coverage.exclusions=**/src/test/java/**,**/static/**,**/templates/**,**/*Test*.java,**/*Tests*.java
sonar.coverage.jacoco.xmlReportPaths=tenantCrm/target/site/jacoco/jacoco.xml
