sonar.sources=tenantCrm/src/main/java,tenantCrm/src/main/resources
sonar.tests=tenantCrm/src/test/java
sonar.exclusions=tenantCrm/src/main/resources/static/**/*,tenantCrm/src/main/resources/templates/**/*
sonar.coverage.exclusions=tenantCrm/src/test/java/**/*,tenantCrm/src/main/resources/static/**/*,tenantCrm/src/main/resources/templates/**/*,**/*Test*.java,**/*Tests*.java
sonar.cpd.exclusions=tenantCrm/src/test/java/**/*,tenantCrm/src/main/resources/static/**/*,tenantCrm/src/main/resources/templates/**/*,**/*Test*.java,**/*Tests*.java
sonar.coverage.jacoco.xmlReportPaths=tenantCrm/target/site/jacoco/jacoco.xml
