sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java
sonar.exclusions=src/main/resources/static/**/*,src/main/resources/templates/**/*
sonar.coverage.exclusions=src/test/java/**/*,src/main/resources/static/**/*,src/main/resources/templates/**/*,**/*Test*.java,**/*Tests*.java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
